
CREATE TABLE public.db_schema_number (
    current_schema_number varchar(4) NOT NULL,
    CONSTRAINT db_schema_number_pkey PRIMARY KEY (current_schema_number)
);
INSERT INTO public.db_schema_number (current_schema_number) VALUES ('0000');

CREATE TABLE public.db_changes_log (
    db_changes_log_id int8 GENERATED BY DEFAULT AS IDENTITY,
    filename text NOT NULL,
    message text NOT NULL,
    deploy_start timestamp NOT NULL,
    deploy_end timestamp NULL,
    CONSTRAINT db_changes_log_pkey PRIMARY KEY (db_changes_log_id)
);

CREATE TABLE public.db_datapop_number (
    current_datapop_number varchar(4) NOT NULL,
    CONSTRAINT db_datapop_number_pkey PRIMARY KEY (current_datapop_number)
);
INSERT INTO public.db_datapop_number (current_datapop_number) VALUES ('0000');
